import logging

ARENA_RATING_CHOICES = [
    "👈  A is better",
    "👉  B is better",
    "🤝  Tie",
    "👎  Both are bad",
]

ARENA_LOGGING_LEVEL = logging.DEBUG

ARENA_NOTICE_MD = """
# ⚔️  AI Reviewer Arena: Benchmarking AI Powered Scientific Paper Reviewers
 [GitHub](https://github.com/) | [Paper](https://arxiv.org/abs/) | [Dataset](https://github.com/) | [Code](https://github.com/)

## 📜 Rules
- Reviewing the manuscript and the reviews generated by the AI systems and vote for the better one!
- Evaluate the quality of the reviews in the following aspects:
  - Technical Quality: Thoroughness and accuracy in assessing the study’s methods, analysis, and scientific rigor.
  - Constructiveness: Helpfulness and actionability of the feedback and suggestions for improvement.
  - Clarity: How well-structured, organized, and clearly communicated the review is.
  - Overall Quality: Holistic assessment of the review’s effectiveness and value.
## 👇 Take a look at the paper first
"""


APP_CSS = """
#model_description_markdown table, #leaderboard table {
    width: 100%;
}

.prose {
    font-size: 105% !important;
}

#arena_leaderboard_dataframe table {
    font-size: 105%;
}
#full_leaderboard_dataframe table {
    font-size: 105%;
}

.tab-nav button {
    font-size: 18px;
}

.chatbot h1 {
    font-size: 130%;
}
.chatbot h2 {
    font-size: 120%;
}
.chatbot h3 {
    font-size: 110%;
}

#chatbot .prose {
    font-size: 90% !important;
}

.sponsor-image-about img {
    margin: 0 20px;
    margin-top: 20px;
    height: 40px;
    max-height: 100%;
    width: auto;
    float: left;
}

.cursor {
    display: inline-block;
    width: 7px;
    height: 1em;
    background-color: black;
    vertical-align: middle;
    animation: blink 1s infinite;
}

.dark .cursor {
    display: inline-block;
    width: 7px;
    height: 1em;
    background-color: white;
    vertical-align: middle;
    animation: blink 1s infinite;
}

@keyframes blink {
    0%, 50% { opacity: 1; }
    50.1%, 100% { opacity: 0; }
}

.app {
  max-width: 100% !important;
  padding-left: 5% !important;
  padding-right: 5% !important;
}

a {
    color: #1976D2; /* Your current link color, a shade of blue */
    text-decoration: none; /* Removes underline from links */
}
a:hover {
    color: #63A4FF; /* This can be any color you choose for hover */
    text-decoration: underline; /* Adds underline on hover */
}

button[aria-label="Clear"][title="Clear"].svelte-xtz2g8.padded {
    display: none;
}

.grading_radio label{
    gap: 10px;
    padding-left:26px;
    padding-right:26px;
    margin-right:12px;
}

#tos_md{
    margin-top: 1em;
}

#ack_md{
    margin-top: 1em;
    margin-bottom: 2em;
}

#leaderboard_stat_md{
    margin-bottom: 2em;
}
"""

TOS_MD = """
### Terms of use
By using this service, users are required to agree to the following terms:
This app is a preview of an ongoing study that provides only very limited safety measures and it may generate 
offensive or inappropriate content. By using this application, users accept the risk of encountering such content and 
the use of this application is entirely at your own risk. The developers, researchers, and associated parties 
disclaim all liability for any damages or losses, including but not limited to direct, indirect, incidental, 
consequential, or punitive damages arising out of your use of or inability to use the application. 
Please click the "Flag" button if you get any inappropriate answer!
"""


ACK_MD = """
### Acknowledgement
The service is a research preview intended for non-commercial use only, it has been built utilizing the open source 
models and tools such as [LLaVA](https://github.com/haotian-liu/LLaVA), [Llama](https://llama.meta.com/), 
[Ollama](https://github.com/ollama/ollama), 
and [Gradio](https://www.gradio.app/).
"""
